name: Update Gradle Wrapper

on:
  schedule:
    - cron: "30 7 * * Mon"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    name: Check for a gradle wrapper update and post PR updating it if one is available
    runs-on: ubuntu-latest

    steps:
      # Check out sources
      - name: Fetch Sources
        uses: actions/checkout@v4.2.1

      # Setup JDK environment for the next steps
      - name: Setup JDK 21
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      # Setup JDK environment for the next steps
      - name: Update Gradle Wrapper When Possible
        uses: gradle-update/update-gradle-wrapper-action@v2.0.0
        with:
          repo-token: ${{ secrets.REPO_PAT }}
